from fpdf import FPDF
import datetime
import os

class IncidentReport(FPDF):
    def header(self):
        # Logo placeholder or Title
        self.set_font('Arial', 'B', 15)
        self.set_text_color(255, 75, 75)
        self.cell(0, 10, 'CAN 2025 GUARDIAN - SECURITY INCIDENT REPORT', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AI Command Center', 0, 0, 'C')

def generate_pdf_report(stats, dominant_mood, threat_image_path=None):
    """
    Generates a PDF incident report based on detected threats and crowd status.
    """
    pdf = IncidentReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Incident Details
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Timestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.cell(0, 10, "Location: Entrance Gate 5 (CAM-024)", 0, 1)
    pdf.ln(5)

    # Security Summary
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Security Summary:", 0, 1)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"- People Count: {stats.get('people_count', 0)}", 0, 1)
    
    threats = stats.get('threats', [])
    if threats:
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, f"- THREATS DETECTED: {', '.join(threats).upper()}", 0, 1)
    else:
        pdf.cell(0, 10, "- No physical threats detected.", 0, 1)
    
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"- Dominant Crowd Mood: {dominant_mood.upper()}", 0, 1)
    pdf.ln(10)

    # Recommended Actions
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Recommended Actions:", 0, 1)
    pdf.set_font("Arial", size=12)
    if threats:
        pdf.cell(0, 10, "1. IMMEDIATE DISPATCH: Security teams to Gate 5.", 0, 1)
        pdf.cell(0, 10, "2. ISOLATION: Flag individual and notify Royal Gendarmerie.", 0, 1)
    if stats.get('crowd_warning'):
        pdf.cell(0, 10, "3. CROWD CONTROL: Open secondary exits at North Stand.", 0, 1)
    pdf.cell(0, 10, "4. LOGGING: Maintain continuous video recording of the area.", 0, 1)

    # Add image if provided
    if threat_image_path and os.path.exists(threat_image_path):
        pdf.ln(10)
        pdf.cell(0, 10, "Incident Evidence (Visual):", 0, 1)
        # Resize image for PDF (approx width 150mm)
        pdf.image(threat_image_path, x=10, w=150)

    report_name = f"incident_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(report_name)
    return report_name
